Options:
  stattrak-line: "&7[&eStatTrak&7] &7Kills: &4%kills%"
  stattrak-weapon-types:
  - "DIAMOND_SWORD"
  - "IRON_SWORD"
  - "DIAMOND_AXE"
  types-on-reload: true
Strings:
  prefix: "&7[&eStatTrak&7]"
  not-stattrakable: "%prefix% &cThis item is &4non-stattrakable&c."
  stattrak-applied: "%prefix% &eStatTrak &7enchancement applied."
  reloaded: "%prefix% &eReloaded."
  no-permission: "%prefix% &cYou lack the needed permission."
  already-stattrak: "%prefix% &cStattrak removed."