name: StatTrak
version: 1.6.1
main: wertik.stattrak.Main
author: Wertik1206
softdepend: [CrazyEnchantments]
commands:
  stattrak:
    description: To add the required lore tho
permission:
  stattrak.apply:
    description: To apply the lore