name: PVPC_StatTrak
version: 1.7
main: wertik.stattrak.Main
author: Wertik1206
commands:
  stattrak:
    description: To add the required lore tho
permission:
  stattrak.apply:
    description: To apply the lore