Options:
  stattrak-line: "%defaultName% %value%"
  value-format: '&7+&c%value%'
  stattrak-weapon-types:
    - "DIAMOND_SWORD"
    - "IRON_SWORD"
    - "DIAMOND_AXE"
    - "BOW"
  stattrak-entity-types:
    - "PLAYER"
    - "PIG"
    - "SLIME"
  types-on-reload: true
Strings:
  prefix: "&8[&eStatTrak&8]"
  not-stattrakable: "%prefix% &cThis item is &4non-stattrakable&c."
  stattrak-applied: "%prefix% &eStatTrak &7enhancement applied."
  reloaded: "%prefix% &7Reloaded."
  no-permission: "%prefix% &cYou lack the needed permission."
  stattrak-reset: "%prefix% &eStatTrak &7reset."
  stattrak-reapplied: "%prefix% &eStatTrak &7enhancement re-applied."
  stattrak-removed: "%prefix% &eStatTrak &7enhancement removed."
normalized-names:
  DIAMOND_SWORD: "Diamond Sword"